# Generated by Django 5.1.2 on 2024-10-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_druncmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='druncmessage',
            name='topic',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
